# Generated by Django 6.0.2 on 2026-02-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('candidat', 'Candidat'), ('commission', 'Commission'), ('admin', 'Administrateur'), ('directeur', 'Directeur'), ('secretaire_general', 'Secrétaire Général')], max_length=30),
        ),
    ]
