# Generated by Django 6.0.2 on 2026-03-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_permission_actionlog_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_no', models.PositiveIntegerField(verbose_name="Numéro d'action")),
                ('action_name', models.CharField(max_length=255, verbose_name="Nom d'action")),
                ('target_role', models.CharField(choices=[('candidat', 'Candidat'), ('commission', 'Membre Commission'), ('responsable_commission', 'Responsable Commission'), ('admin', 'Administrateur')], max_length=30, verbose_name='Rôle cible')),
                ('enabled', models.BooleanField(default=False, verbose_name='Activée')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Action par rôle',
                'verbose_name_plural': 'Actions par rôle',
                'db_table': 'action_role',
                'ordering': ['action_no', 'target_role'],
                'constraints': [models.UniqueConstraint(fields=('action_no', 'target_role'), name='unique_action_role_entry')],
            },
        ),
    ]
