# Generated by Django 5.2.11 on 2026-05-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_user_avatar_url_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialite',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Spécialité'),
        ),
    ]
