# Generated by Django 6.0.2 on 2026-04-12 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature_app', '0008_inscriptionrapprochementaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='candidatures/%Y/%m/%d/')),
                ('nom_fichier_original', models.CharField(max_length=255)),
                ('taille_bytes', models.BigIntegerField()),
                ('format_fichier', models.CharField(max_length=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de traitement'), ('en_cours_ocr', 'OCR en cours'), ('valide', 'Validï¿½'), ('rejete', 'Rejetï¿½'), ('erreur_ocr', "Erreur lors de l'OCR")], default='en_attente', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('donnees_extraites', models.JSONField(blank=True, default=dict)),
                ('score_ocr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('erreur_ocr', models.TextField(blank=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('date_traitement_ocr', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('checksum_sha256', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('diplome', 'Diplï¿½me'), ('releve_notes', 'Relevï¿½ de notes'), ('cv', 'Curriculum Vitae'), ('lettre_motivation', 'Lettre de motivation'), ('certificat_langue', 'Certificat de langue'), ('attestation_travail', 'Attestation de travail'), ('autre', 'Autre')], max_length=50)),
                ('obligatoire', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('taille_max_mb', models.IntegerField(default=5)),
                ('formats_acceptes', models.JSONField(default=list, help_text="Ex: ['pdf', 'jpg', 'png']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type_document'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('soumis', 'Soumis'), ('en_verification', 'En vï¿½rification'), ('incomplet', 'Incomplet'), ('complet', 'Complet'), ('rejete', 'Rejetï¿½')], default='en_cours', max_length=20)),
                ('date_depot', models.DateTimeField(blank=True, null=True)),
                ('date_limite_depot', models.DateTimeField(blank=True, null=True)),
                ('date_derniere_modification', models.DateTimeField(auto_now=True)),
                ('nb_documents_attendus', models.IntegerField()),
                ('nb_documents_soumis', models.IntegerField(default=0)),
                ('score_completude', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-date_depot'],
            },
        ),
        migrations.CreateModel(
            name='ValidationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('accepte', 'Acceptï¿½'), ('rejete', 'Rejetï¿½'), ('en_attente', 'En attente de rï¿½vision')], default='en_attente', max_length=20)),
                ('commentaires', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='candidature',
            new_name='candidature_candida_777088_idx',
            old_name='candidature__candid_5dd8d6_idx',
        ),
        migrations.RenameIndex(
            model_name='candidature',
            new_name='candidature_master__240823_idx',
            old_name='candidature__master__7752df_idx',
        ),
        migrations.RenameIndex(
            model_name='candidature',
            new_name='candidature_statut_7c87ba_idx',
            old_name='candidature__statut_4f743c_idx',
        ),
        migrations.RenameIndex(
            model_name='candidature',
            new_name='candidature_concour_650d6e_idx',
            old_name='candidature__concour_0ab4d0_idx',
        ),
        migrations.RenameIndex(
            model_name='concours',
            new_name='candidature_actif_3f6767_idx',
            old_name='candidature__actif_f2da0b_idx',
        ),
        migrations.RenameIndex(
            model_name='configurationappel',
            new_name='candidature_actif_f2b262_idx',
            old_name='candidature__actif_b6f7a7_idx',
        ),
        migrations.RenameIndex(
            model_name='configurationappel',
            new_name='candidature_date_de_0b7070_idx',
            old_name='candidature__date_de_7f35e7_idx',
        ),
        migrations.RenameIndex(
            model_name='inscriptionrapprochementaudit',
            new_name='candidature_created_f81050_idx',
            old_name='insc_rappr_created_idx',
        ),
        migrations.RenameIndex(
            model_name='master',
            new_name='candidature_actif_caf2a7_idx',
            old_name='candidature__actif_ae24a6_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='candidature_user_id_a5f21d_idx',
            old_name='candidature__user_id_56f820_idx',
        ),
        migrations.AddField(
            model_name='configurationappel',
            name='contenu_offre_edite',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('soumis', 'Soumis'), ('annule', 'AnnulÃ©'), ('sous_examen', 'Sous examen'), ('rejete', 'RejetÃ©/Invalide'), ('preselectionne', 'PrÃ©sÃ©lectionnÃ©'), ('en_attente_dossier', 'En attente de dossier numÃ©rique'), ('dossier_non_depose', 'Dossier non dÃ©posÃ©'), ('dossier_depose', 'Dossier dÃ©posÃ©'), ('en_attente', 'En attente'), ('selectionne', 'SÃ©lectionnÃ©/Admis'), ('inscrit', 'Inscrit')], default='soumis', max_length=30),
        ),
        migrations.AlterField(
            model_name='concours',
            name='type_concours',
            field=models.CharField(choices=[('master', 'Master'), ('ingenieur', 'Cycle IngÃ©nieur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='configurationappel',
            name='date_debut_visibilite',
            field=models.DateField(help_text="Date Ã\xa0 partir de laquelle l'appel est visible"),
        ),
        migrations.AlterField(
            model_name='configurationappel',
            name='date_fin_visibilite',
            field=models.DateField(help_text="Date de fin de visibilitÃ© de l'appel"),
        ),
        migrations.AlterField(
            model_name='donneesacademiques',
            name='mention',
            field=models.CharField(blank=True, choices=[('passable', 'Passable'), ('assez_bien', 'Assez Bien'), ('bien', 'Bien'), ('tres_bien', 'TrÃ¨s Bien')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inscriptionenligne',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('paiement_soumis', 'Paiement soumis'), ('valide', 'ValidÃ©'), ('refuse', 'RefusÃ©')], default='en_attente', max_length=30),
        ),
        migrations.AlterField(
            model_name='listeadmission',
            name='iteration',
            field=models.IntegerField(choices=[(1, 'PremiÃ¨re Liste'), (2, 'DeuxiÃ¨me Liste'), (3, 'TroisiÃ¨me Liste'), (4, 'QuatriÃ¨me Liste')], default=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'SuccÃ¨s'), ('warning', 'Avertissement'), ('danger', 'Danger')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'PayÃ©'), ('echoue', 'Ã‰chouÃ©'), ('rembourse', 'RemboursÃ©')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='objet',
            field=models.CharField(choices=[('score', 'Score incorrect'), ('statut', 'Statut non mis Ã\xa0 jour'), ('dossier', 'ProblÃ¨me de dossier'), ('paiement', 'ProblÃ¨me de paiement'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('en_attente', 'En attente'), ('traitee', 'TraitÃ©e')], default='en_cours', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='candidature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidature_app.candidature'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_documents', to='candidature_app.master'),
        ),
        migrations.AddField(
            model_name='document',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidature_app.documenttype'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='candidature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='candidature_app.candidature'),
        ),
        migrations.AddField(
            model_name='validationdocument',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='candidature_app.document'),
        ),
        migrations.AddField(
            model_name='validationdocument',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='documenttype',
            unique_together={('master', 'type_document')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['candidature', 'statut'], name='candidature_candida_5af87b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['type_document', 'statut'], name='candidature_type_do_bf6de8_idx'),
        ),
    ]
