# Generated by Django 6.0.2 on 2026-05-10 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature_app', '0014_parcours_criteres'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='master',
            name='candidature_actif_caf2a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='offremaster',
            name='candidature_actif_72bbfd_idx',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='delai_depot_dossier',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='delai_paiement',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='delai_preselection',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='master',
        ),
        migrations.AddField(
            model_name='commission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='critereevaluation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='critereevaluation',
            name='nom',
            field=models.CharField(help_text="Nom du champ tel qu'il apparaÃ®t dans le payload (ex: 'moyenne_bac')", max_length=200),
        ),
        migrations.AlterField(
            model_name='parcoursadmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='valeurcritere',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
