# Generated by Django 6.0.2 on 2026-05-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature_app', '0015_remove_master_candidature_actif_caf2a7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcoursadmission',
            name='capacite',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='parcoursadmission',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcoursadmission',
            name='specialite',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='parcoursadmission',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('ouvert', 'Ouvert'), ('ferme', 'FermÃ©')], default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='parcoursadmission',
            name='type',
            field=models.CharField(choices=[('pro', 'Professionnel'), ('recherche', 'Recherche'), ('ingenieur', 'IngÃ©nieur')], default='pro', max_length=20),
        ),
    ]
