# Generated by Django 6.0.2 on 2026-05-12 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature_app', '0016_parcoursadmission_capacite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='decision_finale_responsable',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'ValidÃ©'), ('rejete', 'RejetÃ©')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='membrecommission',
            name='commissions',
            field=models.ManyToManyField(related_name='membre_commission_links', to='candidature_app.commission'),
        ),
        migrations.CreateModel(
            name='AvisMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis', models.BooleanField(help_text='True = favorable, False = dÃ©favorable')),
                ('argument', models.TextField(blank=True)),
                ('date_avis', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_membres', to='candidature_app.candidature')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_membres', to='candidature_app.commission')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='candidature_app.membrecommission')),
            ],
            options={
                'unique_together': {('membre', 'candidature', 'commission')},
            },
        ),
    ]
