# Generated by Django 5.0 on 2026-05-12 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature_app', '0017_candidature_decision_finale_responsable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialiteParcoursMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_formation', models.CharField(choices=[('master', 'Master'), ('ingenieur', 'Cycle IngÃ©nieur')], default='master', max_length=20)),
                ('code_parcours', models.CharField(max_length=50)),
                ('nom_parcours', models.CharField(max_length=200)),
                ('specialites', models.JSONField(blank=True, default=list)),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialites_requises', to='candidature_app.master')),
            ],
            options={
                'ordering': ['ordre', 'nom_parcours'],
                'indexes': [models.Index(fields=['code_parcours'], name='candidature_code_pa_68268c_idx'), models.Index(fields=['type_formation'], name='candidature_type_fo_983e1a_idx')],
                'unique_together': {('code_parcours', 'type_formation')},
            },
        ),
    ]
