# Generated by Django 5.0 on 2026-05-12 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature_app', '0018_specialiteparcoursmapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'EnvoyÃ©e'), ('failed', 'Ã‰chouÃ©e')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='candidature_app.notification')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='candidature_status_ecee64_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, choices=[('soumis', 'Soumis'), ('annule', 'AnnulÃ©'), ('sous_examen', 'Sous examen'), ('rejete', 'RejetÃ©/Invalide'), ('preselectionne', 'PrÃ©sÃ©lectionnÃ©'), ('en_attente_dossier', 'En attente de dossier numÃ©rique'), ('dossier_non_depose', 'Dossier non dÃ©posÃ©'), ('dossier_depose', 'Dossier dÃ©posÃ©'), ('en_attente', 'En attente'), ('selectionne', 'SÃ©lectionnÃ©/Admis'), ('inscrit', 'Inscrit')], max_length=30, null=True)),
                ('nouveau_statut', models.CharField(choices=[('soumis', 'Soumis'), ('annule', 'AnnulÃ©'), ('sous_examen', 'Sous examen'), ('rejete', 'RejetÃ©/Invalide'), ('preselectionne', 'PrÃ©sÃ©lectionnÃ©'), ('en_attente_dossier', 'En attente de dossier numÃ©rique'), ('dossier_non_depose', 'Dossier non dÃ©posÃ©'), ('dossier_depose', 'Dossier dÃ©posÃ©'), ('en_attente', 'En attente'), ('selectionne', 'SÃ©lectionnÃ©/Admis'), ('inscrit', 'Inscrit')], max_length=30)),
                ('raison', models.TextField(blank=True, help_text='Raison du changement de statut')),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('notification_envoyee', models.BooleanField(default=False)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='candidature_app.candidature')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_changement'],
                'indexes': [models.Index(fields=['candidature', '-date_changement'], name='candidature_candida_b9e080_idx'), models.Index(fields=['nouveau_statut'], name='candidature_nouveau_79960f_idx')],
            },
        ),
    ]
