# Generated by Django 6.0.2 on 2026-05-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature_app', '0019_notificationqueue_statushistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avismembre',
            options={'ordering': ['-date_avis']},
        ),
        migrations.AlterField(
            model_name='avismembre',
            name='avis',
            field=models.BooleanField(),
        ),
        migrations.AddIndex(
            model_name='avismembre',
            index=models.Index(fields=['commission', 'date_avis'], name='candidature_commiss_3fe9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='avismembre',
            index=models.Index(fields=['candidature', 'membre'], name='candidature_candida_351be9_idx'),
        ),
    ]
