# Generated by Django 6.0.2 on 2026-05-15

import django
import django.db.models.deletion
from django.db import migrations, models

# CheckConstraint: l'argument `check` a été renommé `condition` dans Django 5.1
# (et `check` supprimé dans Django 6.0). On choisit le bon kwarg selon la version
# installée pour que la migration fonctionne sur .venv (Django < 5.1) ET venv (6.x).
_AVIS_CONDITION = ~models.Q(statut='defavorable') | ~models.Q(commentaire='')
if django.VERSION >= (5, 1):
    _AVIS_CHECK_KWARGS = {'condition': _AVIS_CONDITION}
else:
    _AVIS_CHECK_KWARGS = {'check': _AVIS_CONDITION}


class Migration(migrations.Migration):

    dependencies = [
        ('candidature_app', '0020_alter_avismembre_options_alter_avismembre_avis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('favorable', 'Favorable'), ('defavorable', 'D\xe9favorable')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_avis', models.DateTimeField(auto_now=True)),
                ('is_global', models.BooleanField(default=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_selection', to='candidature_app.commission')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_selection', to='candidature_app.membrecommission')),
            ],
            options={
                'ordering': ['-date_avis'],
            },
        ),
        migrations.AddIndex(
            model_name='avisselection',
            index=models.Index(fields=['commission', 'date_avis'], name='candidature_commiss_1c2a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='avisselection',
            index=models.Index(fields=['membre', 'is_global'], name='candidature_membre__da4949_idx'),
        ),
        migrations.AddConstraint(
            model_name='avisselection',
            constraint=models.UniqueConstraint(fields=('commission', 'membre', 'is_global'), name='unique_global_avis_selection'),
        ),
        migrations.AddConstraint(
            model_name='avisselection',
            constraint=models.CheckConstraint(name='avis_selection_commentaire_required_if_defavorable', **_AVIS_CHECK_KWARGS),
        ),
    ]
