# Generated by Django 6.0.2 on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature_app', '0021_avisselection'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='avisselection',
            new_name='candidature_commiss_33c5ee_idx',
            old_name='candidature_commiss_1c2a2f_idx',
        ),
        migrations.RenameIndex(
            model_name='avisselection',
            new_name='candidature_membre__ef76f0_idx',
            old_name='candidature_membre__da4949_idx',
        ),
        migrations.AddField(
            model_name='commission',
            name='deadline_avis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisselection',
            name='statut',
            field=models.CharField(choices=[('favorable', 'Favorable'), ('defavorable', 'Defavorable')], max_length=20),
        ),
    ]
