# Generated by Django 6.0.2 on 2026-05-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature_app', '0022_rename_candidature_commiss_1c2a2f_idx_candidature_commiss_33c5ee_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='candidature_app.master'),
        ),
    ]
