# Generated by Django 6.0.2 on 2026-05-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature_app', '0023_commission_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='flag_fraude',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidature',
            name='nature_candidature',
            field=models.CharField(choices=[('isimm', 'Ã‰tudiant ISIMM'), ('externe', 'Ã‰tudiant Externe')], default='externe', max_length=10),
        ),
        migrations.AddField(
            model_name='candidature',
            name='note_extraite_ocr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne extraite automatiquement depuis le PDF du dossier (OCR)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='note_saisie_candidat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne dÃ©clarÃ©e par le candidat dans le formulaire de prÃ©inscription', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='score_soumis_front',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='configurationappel',
            name='quota_la',
            field=models.IntegerField(default=0, help_text="Nombre de places en Liste d'Attente"),
        ),
        migrations.AddField(
            model_name='configurationappel',
            name='quota_lp',
            field=models.IntegerField(default=0, help_text='Nombre de places en Liste Principale (admis directs)'),
        ),
    ]
