# Generated by Django 6.0.2 on 2026-06-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature_app', '0025_seed_parcours_specialites'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='avisselection',
            name='avis_selection_commentaire_required_if_defavorable',
        ),
        migrations.AddField(
            model_name='master',
            name='criteres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='master',
            name='score_formule',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
