# Generated by Django 6.0.2 on 2026-06-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature_app', '0026_remove_avisselection_avis_selection_commentaire_required_if_defavorable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='date_saisie_inscription',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='numero_inscription',
            field=models.CharField(blank=True, help_text="NumÃ©ro d'inscription universitaire saisi par le candidat", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='statut_inscription',
            field=models.CharField(choices=[('selectionne', 'SÃ©lectionnÃ©'), ('inscription_saisie', 'Inscription saisie'), ('en_attente_verification', 'En attente de vÃ©rification'), ('inscrit', 'Inscrit confirmÃ©')], default='selectionne', help_text="Statut du processus d'inscription en ligne", max_length=30),
        ),
    ]
